# Generated by Django 5.2.15 on 2026-06-27 02:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.JSONField(default=dict)),
                ('compatibilidade_geral', models.FloatField(blank=True, null=True)),
                ('compatibilidade_tecnica', models.FloatField(blank=True, null=True)),
                ('compatibilidade_comportamental', models.FloatField(blank=True, null=True)),
                ('competencias_atendidas', models.JSONField(blank=True, default=list)),
                ('competencias_ausentes', models.JSONField(blank=True, default=list)),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='interviews.interviewsession')),
                ('job_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='jobs.jobanalysis')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
