# Generated by Django 5.0.6 on 2026-06-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('teste', 'Teste Técnico'), ('entrevista', 'Entrevista'), ('conclusao', 'Conclusão')], default='enviado', max_length=20),
        ),
    ]
