# Generated by Django 5.0.6 on 2026-06-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='question_count',
            field=models.IntegerField(default=0),
        ),
    ]
