# Generated by Django 5.2.15 on 2026-06-27 02:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('curto_prazo', models.JSONField(blank=True, default=list)),
                ('medio_prazo', models.JSONField(blank=True, default=list)),
                ('longo_prazo', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_plan', to='resumes.resume')),
            ],
        ),
    ]
