# Generated by Django 5.2.15 on 2026-06-27 02:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_description', models.TextField()),
                ('hard_skills', models.JSONField(blank=True, default=list)),
                ('soft_skills', models.JSONField(blank=True, default=list)),
                ('tecnologias', models.JSONField(blank=True, default=list)),
                ('certificacoes', models.JSONField(blank=True, default=list)),
                ('idiomas', models.JSONField(blank=True, default=list)),
                ('senioridade', models.CharField(blank=True, max_length=50)),
                ('responsabilidades', models.JSONField(blank=True, default=list)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
